apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        # Delete any existing contents of the directory if it exists.
        #
        # We don't just "rm -rf ${WORKSPACE_SOURCE_PATH}" because ${WORKSPACE_SOURCE_PATH} might be "/"
        # or the root of a mounted volume.
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          # Delete non-hidden files and directories
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          # Delete files and directories starting with . but excluding ..
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          # Delete files and directories starting with .. plus any other character
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint
spec:
  workspaces:
    - name: source
  steps:
    - name: flake8
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eu
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tests
spec:
  workspaces:
    - name: source
  steps:
    - name: nose
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eu
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image
spec:
  params:
    - name: IMAGE
      description: Reference of the image to build and push
      type: string
    - name: DOCKERFILE
      description: Path to Dockerfile relative to workspace
      type: string
      default: ./Dockerfile
    - name: CONTEXT
      description: Build context path
      type: string
      default: .
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/buildah/stable:v1.17.0
      workingDir: $(workspaces.source.path)
      securityContext:
        privileged: true
      env:
        - name: STORAGE_DRIVER
          value: vfs
      script: |
        #!/usr/bin/env sh
        set -eu
        buildah --storage-driver=${STORAGE_DRIVER} bud --tls-verify=false --layers -f $(params.DOCKERFILE) -t $(params.IMAGE) $(params.CONTEXT)
        buildah --storage-driver=${STORAGE_DRIVER} push --tls-verify=false $(params.IMAGE)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
    - name: APP_NAME
      type: string
      default: accounts
    - name: IMAGE
      type: string
  steps:
    - name: rollout
      image: quay.io/openshift/origin-cli:4.10
      script: |
        #!/usr/bin/env sh
        set -eu
        oc set image deployment/$(params.APP_NAME) $(params.APP_NAME)=$(params.IMAGE)
        oc rollout status deployment/$(params.APP_NAME)
